repos:

- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
    - id: black
      args: ["--line-length=127", "./backend"]

- repo: https://github.com/PyCQA/autoflake
  rev: v2.3.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

- repo: https://github.com/timothycrosley/isort
  rev: 5.13.2
  hooks:
    - id: isort
      args: ["--profile", "black", "./backend"]

- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
    - id: flake8
      args: ["--count", "--select=E9,F63,F7,F82", "--show-source", "--statistics", "--max-line-length=127"]

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.56.0
  hooks:
    - id: eslint
      files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
      types: [file]

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
    - id: insert-license
      files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
      args:
        - --license-filepath
        - .precommit-license-header.txt        # defaults to: LICENSE.txt
        - --comment-style
        - /**| |*/        # defaults to:  #

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
    - id: insert-license
      files: \.py$
      args:
        - --license-filepath
        - .precommit-license-header.txt        # defaults to: LICENSE.txt
        - --comment-style
        - "#  "        # defaults to:  #