name: Make Hotfix Branch
on:
  workflow_dispatch:
    inputs:
      source_tag:
        description: 'Starting Tag to make fix from'
        required: true
      dest_tag:
        description: 'New Tag Name'
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  MakeNewBranch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Tag
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ github.event.inputs.source_tag }}
      - name: Create Hotfix Branch and Update Version
        run: |
          git config --global user.email "github_actions@amazon.com"
          git config --global user.name "github_actions_mlspace"
          SRC_TAG=${{ github.event.inputs.source_tag }}
          DST_TAG=${{ github.event.inputs.dest_tag }}
          git checkout -b hotfix/${{ github.event.inputs.dest_tag }}
          sed -i -e "s/\"version\": \"${SRC_TAG:1}\"/\"version\": \"${DST_TAG:1}\"/g" frontend/package.json
          git commit -a -m "updating version for hotfix ${{ github.event.inputs.dest_tag }}"
          git push origin hotfix/${{ github.event.inputs.dest_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}