name: Publish Tag and Draft Release

on:
  pull_request:
    types: [closed]

permissions:
  id-token: write
  contents: write

jobs:
  DraftRelease:
    runs-on: ubuntu-latest
    if: (startsWith(github.event.pull_request.head.ref, 'release/' ) || startsWith(github.event.pull_request.head.ref, 'hotfix/')) && github.event.pull_request.merged == true
    steps:
      - name: Checkout Source Tag
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Get Version
        id: get-version
        run: |
          version=$(echo ${{github.event.pull_request.head.ref}} | cut -d/ -f2)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "VERSION = $version"
      - name: Create Release
        run: |
          gh release create ${{ steps.get-version.outputs.version }} --generate-notes -d -t "${{ steps.get-version.outputs.version }}" --target main
        env:
          GH_TOKEN: ${{ github.token }}