name: Publish Tag and Draft Release

on:
  pull_request:
    branches: ["release/**", "hotfix/**"]
    types: [closed]

permissions:
  id-token: write
  contents: write

jobs:
  MakeNewBranch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Tag
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          commitish: ${{ github.sha }}
