name: Publish Tag and Draft Release

on:
  pull_request:
    types: [closed]

permissions:
  id-token: write
  contents: write

jobs:
  TagAndDraftRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Tag
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Create Release
        run: |
          gh release create v0.0.0 --generate-notes -d -t "${{ github.event.pull_request.base.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
